export interface User {
    // _id: number,
    firstName: string,
    lastName: string,
    username: string,
    email: string,
    // password: number,
    // profileImage: File,
    // profileCover: File,
    // registrationDate: string,
    // profileInfo: string,
    // city: string,
    // birthday: string,
    // education: string,
    // speciality: string,
    gender: 'male' | 'female' | 'unknown',
    // verify: boolean,
    // team: boolean,
    // online: boolean,
}
